#!/usr/bin/env bash
show_help() {
    echo "Usage: pontsun [options] <command> [<args>]"
    echo
    echo "  -h     Print this help."
    echo
    echo "Common commands:"
    echo "  generate-cert [host]   Generates needed ssl certificates"
}

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

OPTIND=1         # Reset in case getopts has been used previously in the shell.

while getopts "hv" opt; do
    case "$opt" in
    h*)
        show_help
        exit 0
        ;;
    esac
done

shift $((OPTIND-1))

[ "${1:-}" = "--" ] && shift

if [ -z $1 ]; then
   show_help
   exit 0
fi

case "$1" in
   generate-cert)
     $DIR/generate-certificates.sh $2
     ;;
   *)
     echo "No such command: $1"
     show_help
     ;;
esac


